'use strict';

// Parity guard: the WASM binding exposes exactly the public surface it declares.
//
// The assertions are exact-set rather than "these names exist", because drift
// runs both ways. A dropped export breaks callers; an export that only this
// binding has is a portability lie -- the same strategy would stop being
// runnable everywhere, which is the whole premise.
//
// This binding is the one that currently diverges, and pinning the set is how
// that stays visible instead of drifting further. Against the streaming surface
// the C ABI declares and the other bindings wrap, WASM:
//   - spells the per-bar feed reach `stepWithRef` (reference series only), where
//     the others take a whole step document and can carry every feed;
//   - spells releasing a run `free` (generated by wasm-bindgen) rather than
//     `close`, and has no `isFinished`;
//   - returns the equity accessors under `equity` / `latestEquity` rather than
//     the `*Json` names its JSON-string returns would suggest.
// Changing any of those must update this list deliberately, not silently.
//
// Build first with
//   wasm-pack build --target nodejs --out-dir pkg
// then run:  node --test tests/completeness.test.cjs
const test = require('node:test');
const assert = require('node:assert');
const wasm = require('../pkg/wickra_backtest_wasm.js');

const EXPORTS = ['StreamingBacktest', 'run', 'run_json', 'version'];
const STREAM_MEMBERS = [
  'equity',
  'finish',
  'free',
  'latestEquity',
  'numTrades',
  'step',
  'stepWithRef',
];

test('wasm module exports exactly the declared surface', () => {
  // `__wasm` is the wasm-bindgen instance handle, not part of the API.
  const exported = Object.keys(wasm)
    .filter((n) => !n.startsWith('__'))
    .sort();
  assert.deepStrictEqual(exported, EXPORTS);
  for (const name of ['run', 'run_json', 'version']) {
    assert.strictEqual(typeof wasm[name], 'function', `missing export ${name}`);
  }
  assert.strictEqual(typeof wasm.StreamingBacktest, 'function');
});

test('wasm streaming class exposes exactly the declared members', () => {
  // `__destroy_into_raw` is wasm-bindgen plumbing behind `free`.
  const members = Object.getOwnPropertyNames(wasm.StreamingBacktest.prototype)
    .filter((n) => n !== 'constructor' && !n.startsWith('__'))
    .sort();
  assert.deepStrictEqual(members, STREAM_MEMBERS);
  for (const name of STREAM_MEMBERS) {
    assert.strictEqual(
      typeof wasm.StreamingBacktest.prototype[name],
      'function',
      `missing member ${name}`,
    );
  }
});
