/* Golden parity for the C ABI: the same fixtures every other binding asserts.
 *
 * Nine language surfaces sit on this ABI, and each had a golden test holding it
 * to golden/expected_json/ -- except the ABI itself, the one they all go
 * through. Its header stayed in sync with cbindgen and its examples ran, so the
 * calls were proven to link and return; nothing proved they returned the right
 * numbers.
 *
 * Each golden/requests/*.json goes through wickra_backtest_run_json and the
 * result is compared byte-for-byte against golden/expected_json/<name>.json,
 * exactly as the C#, Go and Java tests do it. Byte-for-byte rather than parsed:
 * field order and float formatting are part of what the bindings agree on, and
 * a comparison that normalises them would stop noticing when they diverge.
 *
 * Lives in examples/ because that is how these are built here -- the way a
 * consumer builds them, against the installed header and library rather than
 * from inside the Rust tree. CMake registers it as a ctest.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "wickra_backtest.h"

/* The case list is generated by CMake from golden/requests/ at configure time.
 * C has no portable directory walk, and a hand-kept list is the wrong answer:
 * it goes stale by omission, and a fixture nobody listed is not a failure here
 * but an absence -- the one shape of bug this test exists to prevent. */
#include "golden_cases.h"

/* ctest runs from the build directory, so the fixtures are two levels up from
 * examples/c/. Overridable for anyone running the binary by hand. */
static const char *golden_dir(void) {
    const char *env = getenv("WICKRA_GOLDEN_DIR");
    return env ? env : "../../../golden";
}

/* Reads a whole file, or returns NULL. Trailing whitespace is trimmed: the
 * expected files end with a newline and the ABI's output does not. */
static char *read_trimmed(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        return NULL;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        return NULL;
    }
    long size = ftell(f);
    if (size < 0 || fseek(f, 0, SEEK_SET) != 0) {
        fclose(f);
        return NULL;
    }
    char *buf = malloc((size_t)size + 1);
    if (!buf) {
        fclose(f);
        return NULL;
    }
    size_t got = fread(buf, 1, (size_t)size, f);
    fclose(f);
    buf[got] = '\0';
    while (got > 0 && (buf[got - 1] == '\n' || buf[got - 1] == '\r' || buf[got - 1] == ' ')) {
        buf[--got] = '\0';
    }
    return buf;
}

int main(void) {
    const char *dir = golden_dir();
    size_t passed = 0;

    for (size_t i = 0; i < NUM_CASES; i++) {
        char path[512];
        snprintf(path, sizeof(path), "%s/requests/%s.json", dir, CASES[i]);
        char *request = read_trimmed(path);
        if (!request) {
            fprintf(stderr, "cannot read %s\n", path);
            return 1;
        }

        snprintf(path, sizeof(path), "%s/expected_json/%s.json", dir, CASES[i]);
        char *want = read_trimmed(path);
        if (!want) {
            fprintf(stderr, "cannot read %s\n", path);
            free(request);
            return 1;
        }

        char *got = NULL;
        int rc = wickra_backtest_run_json(request, &got);
        free(request);
        if (rc != 0 || got == NULL) {
            fprintf(stderr, "%s: run_json returned %d\n", CASES[i], rc);
            free(want);
            return 1;
        }

        if (strcmp(got, want) != 0) {
            fprintf(stderr, "%s: report differs from the golden fixture\n", CASES[i]);
            fprintf(stderr, "  expected: %.200s\n", want);
            fprintf(stderr, "  actual:   %.200s\n", got);
            wickra_backtest_free_string(got);
            free(want);
            return 1;
        }

        wickra_backtest_free_string(got);
        free(want);
        passed++;
        printf("ok %s\n", CASES[i]);
    }

    printf("golden parity: %zu/%zu cases match\n", passed, NUM_CASES);
    return 0;
}
