/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A backtest driven one bar at a time.
 *
 * `run` needs the whole series up front; this drives the same engine bar by
 * bar, so a live loop and a backtest are the same code path -- feed it from a
 * socket instead of from an array and every value it reports was produced the
 * way the backtest produced it.
 *
 * Like `run`, the reporting methods return JSON strings for the caller to
 * `JSON.parse`, rather than mirroring the whole report shape in napi objects.
 *
 * `finish` consumes the run, which a `&mut self` receiver cannot express, so
 * the engine is held in an `Option` and taken on finish. Using the object
 * afterwards throws instead of resurrecting a half-finished run.
 */
export declare class StreamingBacktest {
  constructor(specJson: string, capital?: number | undefined | null)
  /**
   * Advance by one OHLCV bar. `volume` defaults to 0 and `time` to the number
   * of bars fed so far, matching `run`'s default of `range(len)`.
   */
  step(open: number, high: number, low: number, close: number, volume?: number | undefined | null, time?: number | undefined | null): void
  /**
   * Advance by one bar described as a request document:
   * `{"candle": {...}, "feeds": {...}}`, where `feeds` optionally carries this
   * bar's `reference` / `deriv` / `orderbook` / `trades` / `cross_section`.
   * This is the only form that can drive a strategy reading a side feed.
   */
  stepJson(stepJson: string): void
  /** The equity curve so far, as a JSON array. */
  equityJson(): string
  /** The most recent equity point as JSON, or `null` before the first bar. */
  latestEquityJson(): string
  /** The number of closed trades so far. */
  get numTrades(): number
  /** Whether the run has been finished or closed. */
  get isFinished(): boolean
  /** Close any open position and return the report JSON. Ends the run. */
  finishJson(): string
  /** Drop the run without producing a report. Idempotent. */
  close(): void
}
export type StreamingBacktestNode = StreamingBacktest

/** Run a backtest. Returns the report as a JSON string. */
export declare function run(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>, time: Array<number>, specJson: string, capital?: number | undefined | null): string

/**
 * Run a backtest from a single JSON request bundling candles, spec and optional
 * feeds. Returns the report as a JSON string.
 */
export declare function runJson(requestJson: string): string

/** The crate version. */
export declare function version(): string
