/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Run a backtest. Returns the report as a JSON string. */
export declare function run(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>, time: Array<number>, specJson: string, capital?: number | undefined | null): string
/** The crate version. */
export declare function version(): string
